{
    "name": "Hotel Management",
    "version": "17.0.1.0.0",
    "category": "Addons",
    "summary": "Hotel Management is addons for Odoo 17 to manage hotel",
    "description": """Hotel Management is addons for Odoo 17 to manage hotel""",
    "auhtor": "Nova",
    "company": "PT SOLU FILANTROPI TEKNOLOGI",
    "maintainer": "ERP Team PT SOLU FILANTROPI TEKNOLOGI",
    "depends": ["web", "mail", "product"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/hotel_menu.xml",
        "views/hotel_reservation_view.xml",
        "wizard/hotel_reporting_wizard_view.xml",
        "views/hotel_reporting_template.xml",
        "views/hotel_configuration_amenity_view.xml",
        "views/hotel_configuration_floor_view.xml",
        "views/hotel_configuration_room_view.xml",
        "views/hotel_configuration_service_view.xml",
        "report/hotel_reporting.xml",
        ],
    "assets": {
    },
    "installable": True,
    "auto_install": False,
    "application": False,
}